version: '3.8'
services:

  postgres:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=sasha
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'

volumes:
  postgres:
